const words = [
    { nubian: "Waddē/وضّي", arabic: "توضأ" },
    { nubian: "Sigidē/سِقِدي", arabic: "صلي" },
    { nubian: "Ny/نِي", arabic: "اشرب" },
    { nubian: "Kal/كَل", arabic: "كل" },
    { nubian: "Imbēl/إمَبَل", arabic: "قم" },
    { nubian: "Tēēg/تيق", arabic: "اجلس" },
    { nubian: "Nōg/نوق", arabic: "اذهب" },
    { nubian: "Ta/تا", arabic: "تعال" },
    { nubian: "Ēd/أد", arabic: "تزوج" },
    { nubian: "Bāj/باج", arabic: "طلق" },
    { nubian: "Gorē/قرِّي", arabic: "افرح" },
    { nubian: "Aonj/أونج", arabic: "ابك" },
    { nubian: "Goshi/قوشي", arabic: "اكسر" },
    { nubian: "Gendigir/قيندقر", arabic: "أصلح" },
    { nubian: "Nēēr/نير", arabic: "نم" },
    { nubian: "Bijjy/بجي", arabic: "استيقظ" },
    { nubian: "Bwwy/بوي", arabic: "استحم" },
    { nubian: "Shooky/شووكي", arabic: "اغسل" },
    { nubian: "Sōkē/سوكي", arabic: "ارفع" },
    { nubian: "Aoskor/أوسكر", arabic: "ضع" },
    { nubian: "Kos/كس", arabic: "افتح" },
    { nubian: "Kōb/كوب", arabic: "اقفل" },
    { nubian: "Tō/تو", arabic: "ادخل" },
    { nubian: "Bēl/بيل", arabic: "اخرج" },
    { nubian: "Esa/إسا", arabic: "خذ" },
    { nubian: "Atta/أتا", arabic: "هات" },
    { nubian: "Darry/دري", arabic: "تسلق" },
    { nubian: "Kottē/كتي", arabic: "انزل" },
    { nubian: "Aō/أو", arabic: "غني" },
    { nubian: "Bān/بان", arabic: "ارقص" },
    { nubian: "Āo/آو", arabic: "اعمل" },
    { nubian: "Mog/موق", arabic: "اترك" },
    { nubian: "Banji/بنجي", arabic: "تحدث" },
    { nubian: "Gijir/قجر", arabic: "اسمع" },
    { nubian: "Nal/نل", arabic: "انظر" },
    { nubian: "Gillē/جلي", arabic: "تذكر" },
    { nubian: "Eiw/إيو", arabic: "انس" },
    { nubian: "Aondor/أندر", arabic: "أدخل" },
    { nubian: "Aōs/أوس", arabic: "اخرج" },
    { nubian: "Sām/سام", arabic: "اسكر" },
    { nubian: "Māg/ماق", arabic: "اسرق" },
    { nubian: "Bēr/بير", arabic: "اقتل" },
    { nubian: "rĀ/آر", arabic: "امسك" },
    { nubian: "Mog/مق", arabic: "فك" },
    { nubian: "Digir/دقر", arabic: "اسقط" },
    { nubian: "Jān/جان", arabic: "اشتري" },
    { nubian: "Aēwir/اوير", arabic: "ازرع" },
    { nubian: "Dēēg/ديق", arabic: "اسقِ" },
    { nubian: "Dēg/ديق", arabic: "البس" },
    { nubian: "Digir/دقر", arabic: "اربط" },
    { nubian: "Mokky/مكي", arabic: "اعبر" },
    { nubian: "Kiddy/كدي", arabic: "اغرق" },
    { nubian: "Kajjy/كجي", arabic: "العب" },
    { nubian: "Bāj/باج", arabic: "اكتب" },
    { nubian: "Aosky/أوسكي", arabic: "أنجبي" },
    { nubian: "Kāy/كاي", arabic: "اصنع" },
    { nubian: "Gōnj/قونج", arabic: "ابني" },
    { nubian: "Gōj/قوج", arabic: "اذبح" },
    { nubian: "Ganjy/قنجي", arabic: "احلق" },
    { nubian: "Doky/دوكي", arabic: "اخلع" },
    { nubian: "Jangy/جنقي", arabic: "املأ" },
    { nubian: "Warrn/ورن", arabic: "ابتعد" },
    { nubian: "Jōr/جور", arabic: "حش" },
    { nubian: "Bitty/بتي", arabic: "اجمع" },
    { nubian: "Tēbē/تبي", arabic: "ابحث" },
    { nubian: "Shēg/شق", arabic: "اطعن" },
    { nubian: "Sool/سول", arabic: "احمل" },
    { nubian: "Jigid/جقد", arabic: "امسح" },
    { nubian: "Nij/نج", arabic: "خط" },
    { nubian: "Bōg/بوق", arabic: "اسكب" },
    { nubian: "Bōky/بوي", arabic: "اختبئ" },
    { nubian: "Awir/أوير", arabic: "ادر" },
    { nubian: "Giridē/قريدي", arabic: "تجول" },
    { nubian: "Katty/كتي", arabic: "لف" },
    { nubian: "Awiddy/أودي", arabic: "افرش" },
    { nubian: "Tir/تر", arabic: "اعطي" },
    { nubian: "Gorē/قري", arabic: "افرح" },
    { nubian: "Kililē/كيليلي", arabic: "زغرد" },
    { nubian: "Tob/تب", arabic: "اكنس" },
    { nubian: "Nēw/نيو", arabic: "ارتاح" },
    { nubian: "Sikky/سكي", arabic: "اسأل" },
    { nubian: "Aērggē/أرججي", arabic: "انتظر" },
    { nubian: "Jēd/جد", arabic: "احلف" },
    { nubian: "Fility/فلتي", arabic: "المع" },
    { nubian: "Kērkēr/كركر", arabic: "ارتعش" },
    { nubian: "Tōg/طوق", arabic: "اجلد" },
    { nubian: "Jwm/جوم", arabic: "اضرب" },
    { nubian: "Sonokij/سنوكج", arabic: "اقرص" },
    { nubian: "Weeg/ويج", arabic: "اصرخ" },
    { nubian: "Twky/توك", arabic: "انسج" },
    { nubian: "Joki/جوكي", arabic: "امضغ" },
    { nubian: "Sndi/سندي", arabic: "خف" },
    { nubian: "Tor/تر", arabic: "اطرد" },
    { nubian: "Bēndi/بندي", arabic: "اشحذ" },
    { nubian: "Was/واس", arabic: "اغل" },
    { nubian: "Waddi/وادي", arabic: "احفر" },
    { nubian: "Konjor/كونجور", arabic: "ادفن" },
    { nubian: "Gaki/جاكي", arabic: "اضغط" },
    { nubian: "Bēdi/بيدي", arabic: "عزي" },
  { nubian: "ﻣﻴﺮ Mēr", arabic: "اقطع" },
  { nubian: "ﻗُﻮﻭﺏ Goob", arabic: "أنكِر" },
  { nubian: "ﺑﻘﺘﻲ Bagitē / ﺑِﺸﻜﻲ Bishkē", arabic: "اقسم" },
  { nubian: "ﺗﻮﻟﻲ Tolē", arabic: "اسحب" },
  { nubian: "ﻓِﺮِّﻱ Firry", arabic: "طر" },
  { nubian: "ﺟَﻮﻕ Jwg", arabic: "اطحن" },
  { nubian: "ﻧﻮﺏ Nwb", arabic: "افرُك" },
  { nubian: "ﺗِﻲ Tee", arabic: "قلِّد" },
  { nubian: "ﺳَﻮﻳﺮ Sawir", arabic: "اخلط" },
  { nubian: "ﻣَﻮﻥ Mōn", arabic: "ارفض" },
  { nubian: "ﻛﻮﺩ Kōd", arabic: "اكشط (حك)" },
  { nubian: "ﻛِﺘﻲ Kitē", arabic: "اصمت" },
  { nubian: "ﻗﻮﻟِﻲ Goly", arabic: "ابلع" },
  { nubian: "ﺳُﻮﻛِﻲ Soki", arabic: "سِف" },
  { nubian: "ﺇﺷﻦ Ishin", arabic: "أرسل" },
  { nubian: "ﺷُﻮﻕ Shoog", arabic: "سُق" },
  { nubian: "ﺗُﻮﺑﻲ Tobi", arabic: "ارقد" },
  { nubian: "ﺩﻭﺳﻜﻲ Doski", arabic: "قرقِش" },
  { nubian: "ﺗﻮﺳﻜﻲ Twski", arabic: "كُح" },
  { nubian: "ﺃﻭﺳﻮ Aoso", arabic: "اضحك" },
  { nubian: "ﻭﻳﺪﻱ Widē", arabic: "أرجع/إرجع" },
  { nubian: "ﺩﻭﻧﺞ Dwnj", arabic: "ربي (البشر)" },
  { nubian: "ﺳﺎﻳﻲ Saiē", arabic: "ربي (الحيوانات)" },
  { nubian: "ﺃﺭﻛﻲ Arki", arabic: "ارمِ" },
  { nubian: "ﺳُﻮﻧﺪﻱ Sondē", arabic: "شم" },
  { nubian: "ﺑﺮﺱ Baris", arabic: "استفرغ" },
  { nubian: "ﺩﻭﻭﺭ Door", arabic: "الحق" },
  { nubian: "ﺟﻮﺑﻲ Jwbbē", arabic: "اصبر" },
  { nubian: "ﺳﻮﺗﻲ Sottē / ﺷﺎﺑّﻲ Shabē", arabic: "أسرع" },
  { nubian: "ﻧَﺼﻮ Naso", arabic: "طويل" },
  { nubian: "ﺃُﺭﺗِﻨﺎ Aortina", arabic: "قصير" },
  { nubian: "ﻛَﻮﻣْﺒﻮ Kōmbō", arabic: "سمين" },
  { nubian: "ﺃﻳﺴﻲ Ēsē", arabic: "نحيف" },
  { nubian: "ﺟَﻘَﺪ Jagad", arabic: "ضعيف" },
  { nubian: "ﻣَﺮِﺱ Maris", arabic: "قليل" },
  { nubian: "ﺩِﻗْﺮِﻱ Digry", arabic: "كثير" },
  { nubian: "ﻣَﺲ Mas / ﺗَﻮﻧﺠِﻞ Tonjil", arabic: "جميل" },
  { nubian: "ﻣِﺸِﻨْﺪِﻝ Mishindil", arabic: "قبيح" },
  { nubian: "ﺩُﻭﻝَ Dool / ﺑَﺮِﺝ Barij", arabic: "كبير" },
  { nubian: "ﻛِﻨّﺔ Kinna / ﻧﻮﺭﻭ Nōrō", arabic: "صغير" },
  { nubian: "ﺩُﻭﻟﻮ Dolō", arabic: "ثقيل" },
  { nubian: "ﺷَﻮﺭﻭ Shōrō", arabic: "خفيف" },
  { nubian: "ﺟُﻘْﺮُﻭ Jogro", arabic: "ساخن" },
  { nubian: "ﺃﺭﻭﻓَﻞَ Arōfal", arabic: "بارد" },
  { nubian: "ﻛَﻬﺮْﺗِﻲ ﺑُﻮ Kahartybo", arabic: "دافئ" },
  { nubian: "ﺳﻮّﺩ Sawd", arabic: "يابس" },
  { nubian: "ﺟﺎﻭّﺭ Jaor", arabic: "رطب" },
  { nubian: "ﻧُﻤّﻞ Nomal", arabic: "رائحة زكية" },
  { nubian: "ﺳِﻴّﻞ Sieal", arabic: "رائحة كريهة" },
  { nubian: "ﺇﻧْﻘِﺘَﻞ Ingital", arabic: "حلو" },
  { nubian: "ﻧﺪِّﻱ Naddy", arabic: "مر" },
  { nubian: "ﺑﺼّﺮِﻱ Basarry", arabic: "مسيخ" },
  { nubian: "ﺳﻴﺮﻱ Sērē", arabic: "جيد" },
  { nubian: "ﻣِﻠِﻲ Milly", arabic: "رديء" },
  { nubian: "ﻛَﻮّﺓ Kawwa", arabic: "واسع" },
  { nubian: "ﺗﻜّﺮ Takar", arabic: "ضيق" },
  { nubian: "ﺑَﻮﺟَﻮ Bōjō", arabic: "فضفاض" },
  { nubian: "ﻛَﺮﺟﻴﺒُﻮ Krgybo", arabic: "ناضج" },
  { nubian: "ﺩﻳﺴﻲ Dēsē", arabic: "نيء" },
  { nubian: "ﺃﻳﻘﻴﺘﻲ Aigety", arabic: "قريب" },
  { nubian: "ﻭَﺭِﻱ Wrry", arabic: "بعيد" },
  { nubian: "ﺩﺍ Da", arabic: "موجود" },
  { nubian: "ﺩﺍﻣُﻦ Dāmon", arabic: "غير موجود" },
  { nubian: "ﺟﻨﻘﻲ ﺑﻮ Jangibo", arabic: "ممتلئ" },
  { nubian: "ﺳﻮﺩ Sood", arabic: "فارغ" },
  { nubian: "ﻛَﺎﺭ Kār", arabic: "المنزل" },
  { nubian: "ﻛَﺘَﺮﻱ Katrē", arabic: "الحائط" },
  { nubian: "ﻛﻮﺑﻴﺪ Kwbid", arabic: "الباب" },
  { nubian: "ﻛُﺸَﺮ Koshar", arabic: "المفتاح" },
  { nubian: "ﺃﻧَﻘَﺮﻱ Angarē", arabic: "السرير" },
  { nubian: "ﻧِﺒِﺪ Nibid", arabic: "البرش" },
  { nubian: "ﻛَﺪﻧﺠﻲ Kadēnji", arabic: "الملابس" },
  { arabic: "الملابس", nubian: "كَدنجي/Kadēnji" },
  { arabic: "العمامة", nubian: "كَاسِر/Kasir" },
  { arabic: "المطبخ", nubian: "دِينقَار/Dēngār" },
  { arabic: "الأواني", nubian: "دَادِنْجِي/Dādinji" },
  { arabic: "الطبق", nubian: "أَدَا/Ada" },
  { arabic: "الصاج", nubian: "دِيَو/Dēw" },
  { arabic: "السكين", nubian: "كَندِي/Kandy" },
  { arabic: "النار", nubian: "إِيَق/Eeg" },
  { arabic: "المقص", nubian: "كَيسُور/Kēsor" },
  { arabic: "المرأة", nubian: "كُولَانْج/Kōlanj" },
  { arabic: "الزير", nubian: "قَالُو/Gālō" },
  { arabic: "الكوب", nubian: "كُووس/Koos" },
  { arabic: "الحظيرة", nubian: "زَرْبِي/Zērbē" },
  { arabic: "القفة", nubian: "شُودِي/Shōdy" },
  { arabic: "المزارع", nubian: "تُرْبَل/Tōrbal" },
  { arabic: "الزراعة", nubian: "أَيْوَرِيْت/Aēwreet" },
  { arabic: "الساقية", nubian: "كُولِي/Kōlē" },
  { arabic: "القادوس", nubian: "بَيشِي/Bēshē" },
  { arabic: "الحلقة", nubian: "أَرَقَدِي/Argadē" },
  { arabic: "الحلقة الصغيرة", nubian: "أَرَقَدِينتُود/Argadēntōōd" },
  { arabic: "العمود وسط الساقية", nubian: "دِيَو/Diw" },
  { arabic: "دُلاب الساقية", nubian: "تُورِي/Tōrē" },
  { arabic: "الجدول", nubian: "مَلْتِي/Malty" },
  { arabic: "الجرافة اليدوية", nubian: "أَلْبَل/Albil" },
  { arabic: "الطورية", nubian: "تُبْرَاو/Tobrō" },
  { arabic: "المنجل", nubian: "تُرُب/Torob" },
  { arabic: "الشجر (شجر السنط)", nubian: "جَوِّي/Jwwy" },
  { arabic: "شجر الطلح", nubian: "سَالِي/Sālē" },
  { arabic: "شجر الحراز", nubian: "أُرُج/Aoroj" },
  { arabic: "القرض", nubian: "جُورْتِي/Jorti" },
  { arabic: "البلح", nubian: "بَنتِي/Bnty" },
  { arabic: "الدوم", nubian: "هَمْبُو/Hambo" },
  { arabic: "الحبوب إيو", nubian: "Ew" },
  { arabic: "القمح", nubian: "إِيلي/Illē" },
  { arabic: "الذرة الرفيعة", nubian: "مَري/Mary" },
  { arabic: "الذرة الشامية", nubian: "مَكَاذَة/Mkada" },
  { arabic: "البذور", nubian: "تِيَرِي/Tēri" },
  { arabic: "البطيخ", nubian: "تِمي/Timē" },
  { arabic: "القرع", nubian: "كَبِي/Kēbē" },
  { arabic: "اللوبيا", nubian: "أَشْرَنْكِي/Ashrankē" },
  { arabic: "البامية", nubian: "أَوِي/Aōi" },
  { arabic: "البصل", nubian: "بِلي/Belē" },
  { arabic: "الترمس", nubian: "أَنْقَلَنج/Anglanj" },
  { arabic: "القصب", nubian: "حَقِي/Hagē" },
  { arabic: "القش", nubian: "قِيِيد/Geed" },
  { arabic: "الحلفاء", nubian: "هَمَرَتِي/Hamartē" },
  { arabic: "الأسد", nubian: "كَو/Kō" },
  { arabic: "الثور", nubian: "قُر/Gor" },
  { arabic: "البقرة", nubian: "تِي/Tiy" },
  { arabic: "العجل", nubian: "قُرْتُود/Gortōōd" },
  { arabic: "الحمار", nubian: "هَنٌو/Hano" },
  { arabic: "الحصان", nubian: "كَجَKaj" },
  { arabic: "الجمل", nubian: "كَم/Kam" },
  { arabic: "الغزال", nubian: "قَيِل/Gēēl" },
  { arabic: "النعجة", nubian: "أَيْقِيد/Aigēd" },
  { arabic: "الماعز", nubian: "بَرْتِي/Brty" },
  { arabic: "التيس", nubian: "بُتُل/Botol" },
  { arabic: "البهائم", nubian: "أَوْرْتِنْجِي/Aortingy" },
  { arabic: "الثعبان", nubian: "كَاغ/Kāg" },
  { arabic: "العقرب", nubian: "إِيجيِن/Ijeen" },
  { arabic: "الدجاجة", nubian: "دُمَرِي/Domarē" },
  { arabic: "الحرباء", nubian: "نُونْقَادِسِي/Nongadēsē" },
  { arabic: "السحلية", nubian: "جَنْجَلِسِي/Gangalisē" },
  { arabic: "الضب", nubian: "كُرَانْج/Korranj" },
  { arabic: "الطائر", nubian: "فَوْجَة/Fōga" },
  { arabic: "الكلب", nubian: "وَل/Wal" },
  { arabic: "القط", nubian: "سَاب/Sāb" },
  { arabic: "الفأر", nubian: "بُرُكِي/Boroky" },
  { arabic: "الثعلب", nubian: "أَيْوْكَوْل/Aēwkōl" },
  { arabic: "الذئب", nubian: "أَيْدِي/Ēddi" },
  { arabic: "التمساح", nubian: "أَيْلُم/Ailom" },
  { arabic: "الورل", nubian: "أَشَكِي/Ashky" },
  { arabic: "السمكة", nubian: "كَارِي/Kārē" },
  { arabic: "سرطان البحر", nubian: "سُنْتِي كَبِيش/Sontikbish" },
  { arabic: "السلاحف", nubian: "دَرِق/Darig" },
  { arabic: "الضفدع", nubian: "قَوْقَلَتِي/Goglaty" },
  { arabic: "الجرايدة", nubian: "بَنگَا/Bnga" },
  { arabic: "الذباب", nubian: "كُلْتِي/Kolty" },
  { arabic: "النملة", nubian: "قَوْر/Gōōr" },
  { arabic: "النمل الأبيض", nubian: "نُورِي/Norē" },
  { arabic: "خلف", nubian: "أَبَاق/Abāg" },
  { arabic: "فوق", nubian: "دُوقَوْر/Dōgōr" },
  { arabic: "تحت", nubian: "تُوقَوْر/Tōgōr" },
    { arabic: "هنا", nubian: "اِندو/Indō" },
    { arabic: "هناك", nubian: "مَندُو/Mandō" },
    { arabic: "الشمال", nubian: "كنير/Knēēr" },
    { arabic: "الجنوب", nubian: "أونقور/Aōngōōr" },
    { arabic: "الشرق", nubian: "ملتي/Malty" },
    { arabic: "الغرب", nubian: "تينقار/Tingar" },
    { arabic: "هذا", nubian: "إن/In" },
    { arabic: "ذاك", nubian: "من/Man" },
    { arabic: "هؤلاء", nubian: "إنقو/Ingo" },
    { arabic: "أولئك", nubian: "منقو/Mango" },
    { arabic: "الأبيض", nubian: "أرو/Arō" },
    { arabic: "الأسود", nubian: "أورمي/Aoromē" },
    { arabic: "الأخضر", nubian: "دسي/Dēsē" },
    { arabic: "الأحمر", nubian: "قيلي/Gēēlē" },
    { arabic: "الشمس", nubian: "مسيل/Masil" },
    { arabic: "القمر", nubian: "أونتي/Aōnaty" },
    { arabic: "النجمة", nubian: "وسّي/Wissy" },
    { arabic: "المطر", nubian: "أرو/Aro" },
    { arabic: "الرعد", nubian: "أودودا/Odooda" },
    { arabic: "البرد", nubian: "أود/Aōd" },
    { arabic: "الرياح", nubian: "ترُق/Torog" },
    { arabic: "المرض", nubian: "أودي/Aodē" },
    { arabic: "المريض", nubian: "أودي بو/Aodybo" },
    { arabic: "ألم البطن", nubian: "توندي/Toonōdē" },
    { arabic: "ألم الرأس", nubian: "أورأودي/Aorōdē" },
    { arabic: "الحمى", nubian: "وردى/Wirdē" },
    { arabic: "المكسور في العظام", nubian: "قوشي بو/Goshybo" },
    { arabic: "المشقوق في العظام", nubian: "قق بو/Gagbo" },
    { arabic: "المفكوك في العظام", nubian: "بد بو/Bodbo" },
    { arabic: "الأطرش", nubian: "ترِق/Tarig" },
    { arabic: "الأبكم", nubian: "مُمُد/Momod" },
    { arabic: "الأعمى", nubian: "دُنقُر/Dongor" },
    { arabic: "المجنون", nubian: "دَهَلْكُول/Dhlkōl" },
    { arabic: "الميت", nubian: "دي بو/Dybo" },
    { arabic: "ماذا؟", nubian: "منقي/Mingy" },
    { arabic: "متى؟", nubian: "سنتا تكّي/Sintatki" },
    { arabic: "من؟", nubian: "نيتي/Nitē" },
    { arabic: "لماذا؟", nubian: "ملّر/Milar" },
    { arabic: "أين؟", nubian: "إسير/Isair" },
    { arabic: "حقاً؟", nubian: "أليري/Alērē" },
    { arabic: "يا ترى؟", nubian: "أبلايا/Abaya" },
    { arabic: "الله", nubian: "أرتي/Arti" },
    { arabic: "الملك", nubian: "أور/Awr" },
    { arabic: "الصلاة", nubian: "سقدِر/Sigidar" },
    { arabic: "العيد", nubian: "كوري/Kōrē" },
    { arabic: "الاسم", nubian: "أرري/Aērry" },
    { arabic: "الرجل", nubian: "أوقِج/Aogij" },
    { arabic: "المرأة", nubian: "أينَ/Aēn" },
    { arabic: "الابن", nubian: "بتان/Bitan" },
    { arabic: "الطفل", nubian: "شافوت/Shafoot" },
    { arabic: "الروح", nubian: "نَيورتي/Nēwērty" },
    { arabic: "اللحم", nubian: "كوسو/Koso" },
    { arabic: "العظم", nubian: "كيد/Keed" },
    { arabic: "العصب", nubian: "كوي/Kwy" },
    { arabic: "الدم", nubian: "قيّو/Gēw" },
    { arabic: "العرق", nubian: "تِلَّتي/Tilatti" },
    { arabic: "الإنسان", nubian: "أدَمَ/Adam" },
    { arabic: "الضيف", nubian: "إشكرتي/Eshkarty" },
    { arabic: "الجزيرة", nubian: "آرتي/Ārty" },
    { arabic: "رأس الجزيرة الشمالي", nubian: "ساب/Sāb" },
    { arabic: "رأس الجزيرة الجنوبي", nubian: "كونج/Kōnj" },
    { arabic: "البحر", nubian: "أورُو/Aoro" },
    { arabic: "المركب", nubian: "كب/Kob" },
    { arabic: "القيف", nubian: "أوبول/Aōbōl" },
    { arabic: "تحت القيف", nubian: "أوبول توقو/Aōbōltōgō" },
    { arabic: "فوق القيف", nubian: "أوبول كوجر/Aōbōlkōgir" },
    { arabic: "الماء", nubian: "ايسي/Aēsy" },
    { arabic: "الحجر", nubian: "كُﻠُﻮ Kolo" },
    { arabic: "الرمل", nubian: "سِﻴِﻮ Sew" },
    { arabic: "التراب", nubian: "أيسكīd Aeskēd" },
    { arabic: "الطين", nubian: "سِﺒﻲ Sibē" },
    { arabic: "المال", nubian: "دُونقِّﻲ Dongy" },
    { arabic: "الذهب", nubian: "نَوبَري Nōbrē" },
    { arabic: "الحديد", nubian: "شَارﺗﻲ Sharti" },
    { arabic: "الخشب", nubian: "بِير Bēr" },
    { arabic: "الحليب", nubian: "إِﺟِﻲ Ejjy" },
    { arabic: "البيض", nubian: "كُﻤْﺒُﻮ Kombo" },
    { arabic: "الدقيق", nubian: "نَورﺗِﻲ Nōrty" },
    { arabic: "الملح", nubian: "أومبُﺪ Aombod" },
    { arabic: "العطرون", nubian: "جَدِّﻱ Jddi" },
    { arabic: "الظل", nubian: "أولِﻲ Aōly" },
    { arabic: "الجماعة من الناس", nubian: "شُوقَﻮر Shogar" },
    { arabic: "الجميع", nubian: "مَﻠّﻲ Malē" },
    { arabic: "العبد", nubian: "نُقُد Nogod" },
    { arabic: "الحد", nubian: "كِيل Kēl" },
    { arabic: "المكان", nubian: "أَقرّ Agar" },
    { arabic: "الحي", nubian: "مَار Mar" },
    { arabic: "المكان المرتفع", nubian: "كُتِّﻲ Kotty" },
    { arabic: "الكذب", nubian: "مُرسِﻲ Morsy" },
    { arabic: "نعم", nubian: "أَيّو Aēw" },
    { arabic: "لا", nubian: "وَارَا Wara" },
    { arabic: "حاضر", nubian: "سَرِي Sērē" },
    { arabic: "ملكي", nubian: "أَندِﻱ Andy" },
    { arabic: "صاحب الشيء", nubian: "تِرْتِﻲ Tirty" },
    { arabic: "يا النداء", nubian: "وَو Wo" },
    { arabic: "تقريبًا", nubian: "كِرﻱ Kiri" },
    { arabic: "احتمال", nubian: "أَدّﻭﺭ Addor" },
    { arabic: "هكذا", nubian: "إِنْكِيقِي Inkēgi" },
    { arabic: "البئر", nubian: "قَوِّي Gawwi" },
    { arabic: "الحبل", nubian: "إِرﻱ Ery" },
    { arabic: "الشوك", nubian: "كِنسِي Kinesē" },
    { arabic: "الذنب", nubian: "أَيّو Aēw" },
    { arabic: "البصير", nubian: "أَشِّد Ashid" },
    { arabic: "الحداد", nubian: "تَبِد Tabid" },
    { arabic: "الوداع", nubian: "خَيْرُوي Khērwē" },
    { arabic: "أنتَ/أنتِ", nubian: "أَر Ēr" },
    { arabic: "هو/هي", nubian: "تَر Tēr" },
    { arabic: "نحن", nubian: "أَي Ai أَيْقُو Aigo" },
    { arabic: "أنتم", nubian: "إِر Ir إِرْقُو Irgo" },
    { arabic: "الابن", nubian: "تَود/Tōd" },
    { arabic: "البنت", nubian: "بُرُو/Boro" },
    { arabic: "الحفيد", nubian: "أَسِّي/Assy" },
    { arabic: "ابن الحفيد", nubian: "ويسّي/Wissy" },
    { arabic: "حفيد الحفيد", nubian: "كَلَانَج/Kalanj" },
    { arabic: "السبت", nubian: "سَمْتِي/Smtē" },
    { arabic: "الأحد", nubian: "كِرَاقِي/Kiragē" },
    { arabic: "الإثنين", nubian: "بُوش/Bosh" },
    { arabic: "الثلاثاء", nubian: "بُوشنَنج/Boshnnj" },
    { arabic: "الجمعة", nubian: "مُوشَنِي/Moshnē" },
    { arabic: "اليوم", nubian: "إنّوِي/Innwy" },
    { arabic: "أمس", nubian: "وِيْل/Weel" },
    { arabic: "أمس الأول", nubian: "كَمِس/Kamis" },
    { arabic: "أول أمس الأول", nubian: "كَمِس نُوقُل/Kamisnōgōl" },
    { arabic: "غداً", nubian: "أَصَل/Asal" },
    { arabic: "بعد غد", nubian: "أَصَل وَحَد/Asalwahad" },
    { arabic: "الليل", nubian: "أُقْو/Aogo" },
    { arabic: "النهار", nubian: "أُقْرِيس/Aogrēs" },
    { arabic: "العصر", nubian: "شَارَا/Shara" },
    { arabic: "الآن", nubian: "إِنْكِنِيغِي/Inkēnēgy" },
    { arabic: "واحد", nubian: "وِيرِي/Wēry" },
    { arabic: "اثنان", nubian: "أَوِي/Awwy" },
    { arabic: "ثلاثة", nubian: "تُوسْكِي/Tosky" },
    { arabic: "أربعة", nubian: "كَمْسِي/Kmsy" },
    { arabic: "خمسة", nubian: "دِجِي/Dijy" },
    { arabic: "ستة", nubian: "قَرْجِي/Gorjy" },
    { arabic: "سبعة", nubian: "كُولُودِي/Kolody" },
    { arabic: "ثمانية", nubian: "إِدُوِي/Idwy" },
    { arabic: "تسعة", nubian: "إِسْكُودِي/Iskody" },
    { arabic: "عشرة", nubian: "دِمْنِي/Dimny" },
    { arabic: "أحد عشر", nubian: "دَمْنَدُوِيَرِي/Dimndwery" },
    { arabic: "اثنا عشر", nubian: "دَمْنَدْأَوِي/Dimndawwy" },
    { arabic: "ثلاثة عشر", nubian: "دَمْنَدْتُوسْكِي/Dimndtosky" },
    { arabic: "أربعة عشر", nubian: "دَمْنَدْكَمْسِي/Dimndkmsy" },
    { arabic: "خمسة عشر", nubian: "دَمْنَدْجِّي/Dimnddijy" },
    { arabic: "ستة عشر", nubian: "دَمْنَدْقَرْجِي/Dimndgorjy" },
    { arabic: "سبعة عشر", nubian: "دَمْنَدْكُولُودِي/Dimndkolody" },
    { arabic: "ثمانية عشر", nubian: "دَمْنَدْإِدُوِي/Dimndidwy" },
    { arabic: "تسعة عشر", nubian: "دَمْنَدْإِسْكُودِي/Dimndiskody" },
    { arabic: "عشرون", nubian: "أَرِي/Arē" },
    { arabic: "ثلاثون", nubian: "تُوسْكَأَوْنَد/Toskaond" },
    { arabic: "أربعة وثلاثون", nubian: "كَمْسَأَوْنَد/Kmsaond" },
    { arabic: "خمسة وثلاثون", nubian: "دِجَأَوْنَد/Dijaond" },
    { arabic: "ستون", nubian: "قَرْجَأَوْنَد/Gorjaond" },
    { arabic: "سبعون", nubian: "كُولُودَأَوْنَد/Kolodaond" },
    { arabic: "ثمانون", nubian: "إِدُوَأَوْنَد/Idoaond" },
    { arabic: "تسعون", nubian: "إِسْكُودَأَوْنَد/Iskodaond" },
    { arabic: "مئة", nubian: "إِيمِيْل/Imil" },
    { arabic: "ألف", nubian: "دُورِيَّة/Dōrē" },
    { arabic: "مليون", nubian: "دُورِيَّة دُورِيَّة/DōrēDōrē" },
    { arabic: "الرأس", nubian: "أُرْ/ Aor" },
    { arabic: "الشعر", nubian: "دِلْتِي/Dilti" },
    { arabic: "الوجه", nubian: "كُونَج/Konj" },
    { arabic: "الخد", nubian: "تِمْل/Timil" },
    { arabic: "العين", nubian: "مِسِي/Missi" },
    { arabic: "الأذن", nubian: "أُلق/Aolog" },
    { arabic: "الأنف", nubian: "صَوْرِنَج/Sorinj" },
    { arabic: "الشفاه", nubian: "شُونِدي/Shondi" },
    { arabic: "الفم", nubian: "أَقِل/Agil" },
    { arabic: "اللسان", nubian: "نِيْد/Nēd" },
    { arabic: "السن", nubian: "نَل/Nal" },
    { arabic: "الرّقبة", nubian: "قُمُر/Gomor" },
    { arabic: "الحلق", nubian: "قَوْس/Gōs" },
    { arabic: "الكتف", nubian: "أُوسْمَر/Aosmar" },
    { arabic: "الظهر", nubian: "جِير/Gēr" },
    { arabic: "البطن", nubian: "تُو/Too" },
    { arabic: "الصدر", nubian: "أَوْك/Awk" },
    { arabic: "القلب", nubian: "آء/Āā" },
    { arabic: "اليد", nubian: "إِي/Ee" },
    { arabic: "الإصبع", nubian: "صَرْبِي/Srbē" },
    { arabic: "الظفر", nubian: "سُنْتِي/Sonti" },
    { arabic: "الركبة", nubian: "كُرْتِي/Korty" },
    { arabic: "الرجل", nubian: "أَوْصِي/Aōsy" }
];